# version:   "0000--12-Sep-2022"
copyright:   "2022"
author:      "syafiqoarashy"
name:        "Syafiqo Arashy Octaviano"
title:       "OS222: Operating Systems 2022-2"
githublink:  "https://github.com/syafiqoarashy/os222/"
myloglink:   "/TXT/mylog.txt"
encoding:    UTF-8
markdown:    kramdown
input:       GFM
hard_wrap:   false
github:      [metadata]
